#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function, division, unicode_literals

import sys
import tohaml

usage = \
"""
toHAML - an HTML to HAML converter
the particular dialect of HAML is 
HAMLPY (https://github.com/jessemiller/HamlPy)

usage: tohaml.py .html
"""


if __name__ == '__main__':
  if len(sys.argv) < 2:
    print(usage)
  else:
    if len(sys.argv) > 2:
      out_f = codecs.open(sys.argv[2], 'w', encoding='utf-8')
    else:
      out_f = sys.stdout
    print_haml(sys.argv[1], out_f)

